(define (problem zeno-4) (:domain zeno-travel)
(:customization
(= :time-format "%d/%m/%Y %H:%M:%S")
(= :time-horizon-relative 2500)
(= :time-start "05/06/2007 08:00:00")
(= :time-unit :hours))

(:objects
    p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 - person
    almeria barcelona bilbao cadiz cordoba gibraltar granada huelva jaen madrid malaga sevilla - city
    a1 a2 a3 a4 a5 a6 a7 - aircraft
)
(:init
    (at p1 madrid)
    (at p2 madrid)
    (at p3 madrid)
    (at p4 madrid)
    (at p5 madrid)
    (at p6 madrid)
    (at p7 madrid)
    (at p8 madrid)
    (at p9 madrid)
    (at p10 madrid)
    (at p11 madrid)
    (at p12 madrid)
    (at p13 madrid)
    (at p14 madrid)
    (at p15 madrid)
    (at p16 barcelona)
    (at p17 barcelona)
    (at p18 barcelona)
    (at p19 huelva)
    (at p20 huelva)
    (at p21 huelva)
    (at p22 huelva)
    (at p23 huelva)
    (at p24 huelva)
    (at p25 huelva)

    (at a1 bilbao)
    (at a2 bilbao)
    (at a3 bilbao)
    (at a4 gibraltar)
    (at a5 gibraltar)
    (at a6 cadiz)
    (at a7 cadiz)

    (destino p1 cadiz)
    (destino p2 cadiz)
    (destino p3 cadiz)
    (destino p4 cadiz)
    (destino p5 cadiz)
    (destino p6 granada)
    (destino p7 granada)
    (destino p8 granada)
    (destino p9 granada)
    (destino p10 granada)
    (destino p11 jaen)
    (destino p12 jaen)
    (destino p13 jaen)
    (destino p14 jaen)
    (destino p15 jaen)
    (destino p16 bilbao)
    (destino p17 bilbao)
    (destino p18 bilbao)
    (destino p19 bilbao)
    (destino p20 bilbao)
    (destino p21 huelva)
    (destino p22 huelva)
    (destino p23 huelva)
    (destino p24 huelva)
    (destino p25 huelva)

    (= (numero-de-pasajeros a1) 0)
    (= (capacidad-maxima a1) 3)

    (= (numero-de-pasajeros a2) 0)
    (= (capacidad-maxima a2) 3)

    (= (numero-de-pasajeros a3) 0)
    (= (capacidad-maxima a3) 10)

    (= (numero-de-pasajeros a4) 0)
    (= (capacidad-maxima a4) 10)

    (= (numero-de-pasajeros a5) 0)
    (= (capacidad-maxima a5) 5)

    (= (numero-de-pasajeros a6) 0)
    (= (capacidad-maxima a6) 7)

    (= (numero-de-pasajeros a7) 0)
    (= (capacidad-maxima a7) 3)

    (= (fuel-limit a1) 5136) ; 4 viajes * 1284 (distancia máxima Barcelona-Cádiz)
    (= (fuel-limit a2) 5136)
    (= (fuel-limit a3) 5136)
    (= (fuel-limit a4) 5136)
    (= (fuel-limit a5) 5136)
    (= (fuel-limit a6) 5136)
    (= (fuel-limit a7) 5136)

    (= (duration-limit a1) 100)
    (= (duration-limit a2) 100)
    (= (duration-limit a3) 50)
    (= (duration-limit a4) 70)
    (= (duration-limit a5) 70)
    (= (duration-limit a6) 500)
    (= (duration-limit a7) 500)

    (= (distance almeria barcelona) 809)
    (= (distance almeria bilbao) 958)
    (= (distance almeria cadiz) 463)
    (= (distance almeria cordoba) 316)
    (= (distance almeria gibraltar) 339)
    (= (distance almeria granada) 162)
    (= (distance almeria huelva) 505)
    (= (distance almeria jaen) 220)
    (= (distance almeria madrid) 547)
    (= (distance almeria malaga) 207)
    (= (distance almeria sevilla) 410)

    (= (distance barcelona almeria) 809)
    (= (distance barcelona bilbao) 620)
    (= (distance barcelona cadiz) 1284)
    (= (distance barcelona cordoba) 908)
    (= (distance barcelona gibraltar) 1124)
    (= (distance barcelona granada) 868)
    (= (distance barcelona huelva) 1140)
    (= (distance barcelona jaen) 804)
    (= (distance barcelona madrid) 621)
    (= (distance barcelona malaga) 997)
    (= (distance barcelona sevilla) 1046)

    (= (distance bilbao almeria) 958)
    (= (distance bilbao barcelona) 620)
    (= (distance bilbao cadiz) 1058)
    (= (distance bilbao cordoba) 796)
    (= (distance bilbao gibraltar) 1110)
    (= (distance bilbao granada) 829)
    (= (distance bilbao huelva) 939)
    (= (distance bilbao jaen) 730)
    (= (distance bilbao madrid) 395)
    (= (distance bilbao malaga) 939)
    (= (distance bilbao sevilla) 933)

    (= (distance cadiz almeria) 463)
    (= (distance cadiz barcelona) 1284)
    (= (distance cadiz bilbao) 1058)
    (= (distance cadiz cordoba) 261)
    (= (distance cadiz gibraltar) 124)
    (= (distance cadiz granada) 296)
    (= (distance cadiz huelva) 214)
    (= (distance cadiz jaen) 330)
    (= (distance cadiz madrid) 654)
    (= (distance cadiz malaga) 240)
    (= (distance cadiz sevilla) 126)

    (= (distance cordoba almeria) 316)
    (= (distance cordoba barcelona) 908)
    (= (distance cordoba bilbao) 796)
    (= (distance cordoba cadiz) 261)
    (= (distance cordoba gibraltar) 294)
    (= (distance cordoba granada) 160)
    (= (distance cordoba huelva) 241)
    (= (distance cordoba jaen) 108)
    (= (distance cordoba madrid) 396)
    (= (distance cordoba malaga) 165)
    (= (distance cordoba sevilla) 143)

    (= (distance gibraltar almeria) 339)
    (= (distance gibraltar barcelona) 1124)
    (= (distance gibraltar bilbao) 1110)
    (= (distance gibraltar cadiz) 124)
    (= (distance gibraltar cordoba) 294)
    (= (distance gibraltar granada) 255)
    (= (distance gibraltar huelva) 289)
    (= (distance gibraltar jaen) 335)
    (= (distance gibraltar madrid) 662)
    (= (distance gibraltar malaga) 134)
    (= (distance gibraltar sevilla) 201)

    (= (distance granada almeria) 162)
    (= (distance granada barcelona) 868)
    (= (distance granada bilbao) 829)
    (= (distance granada cadiz) 296)
    (= (distance granada cordoba) 160)
    (= (distance granada gibraltar) 255)
    (= (distance granada huelva) 346)
    (= (distance granada jaen) 93)
    (= (distance granada madrid) 421)
    (= (distance granada malaga) 125)
    (= (distance granada sevilla) 252)

    (= (distance huelva almeria) 505)
    (= (distance huelva barcelona) 1140)
    (= (distance huelva bilbao) 939)
    (= (distance huelva cadiz) 214)
    (= (distance huelva cordoba) 241)
    (= (distance huelva gibraltar) 289)
    (= (distance huelva granada) 346)
    (= (distance huelva jaen) 347)
    (= (distance huelva madrid) 591)
    (= (distance huelva malaga) 301)
    (= (distance huelva sevilla) 95)

    (= (distance jaen almeria) 220)
    (= (distance jaen barcelona) 804)
    (= (distance jaen bilbao) 730)
    (= (distance jaen cadiz) 330)
    (= (distance jaen cordoba) 108)
    (= (distance jaen gibraltar) 335)
    (= (distance jaen granada) 93)
    (= (distance jaen huelva) 347)
    (= (distance jaen madrid) 335)
    (= (distance jaen malaga) 203)
    (= (distance jaen sevilla) 246)

    (= (distance madrid almeria) 547)
    (= (distance madrid barcelona) 621)
    (= (distance madrid bilbao) 395)
    (= (distance madrid cadiz) 654)
    (= (distance madrid cordoba) 396)
    (= (distance madrid gibraltar) 662)
    (= (distance madrid granada) 421)
    (= (distance madrid huelva) 591)
    (= (distance madrid jaen) 335)
    (= (distance madrid malaga) 532)
    (= (distance madrid sevilla) 524)

    (= (distance malaga almeria) 207)
    (= (distance malaga barcelona) 997)
    (= (distance malaga bilbao) 939)
    (= (distance malaga cadiz) 240)
    (= (distance malaga cordoba) 165)
    (= (distance malaga gibraltar) 134)
    (= (distance malaga granada) 125)
    (= (distance malaga huelva) 301)
    (= (distance malaga jaen) 203)
    (= (distance malaga madrid) 532)
    (= (distance malaga sevilla) 209)

    (= (distance sevilla almeria) 410)
    (= (distance sevilla barcelona) 1046)
    (= (distance sevilla bilbao) 933)
    (= (distance sevilla cadiz) 126)
    (= (distance sevilla cordoba) 143)
    (= (distance sevilla gibraltar) 201)
    (= (distance sevilla granada) 252)
    (= (distance sevilla huelva) 95)
    (= (distance sevilla jaen) 246)
    (= (distance sevilla madrid) 534)
    (= (distance sevilla malaga) 209)

    (= (fuel a1) 2500)
    (= (slow-speed a1) 10)
    (= (fast-speed a1) 20)
    (= (slow-burn a1) 1)
    (= (fast-burn a1) 2)
    (= (capacity a1) 2500)
    (= (refuel-rate a1) 1)

    (= (fuel a2) 1000)
    (= (slow-speed a2) 5)
    (= (fast-speed a2) 10)
    (= (slow-burn a2) 1)
    (= (fast-burn a2) 2)
    (= (capacity a2) 2500)
    (= (refuel-rate a2) 1)

    (= (fuel a3) 10)
    (= (slow-speed a3) 50)
    (= (fast-speed a3) 100)
    (= (slow-burn a3) 4)
    (= (fast-burn a3) 10)
    (= (capacity a3) 10000)
    (= (refuel-rate a3) 1)

    (= (fuel a4) 100)
    (= (slow-speed a4) 20)
    (= (fast-speed a4) 60)
    (= (slow-burn a4) 2)
    (= (fast-burn a4) 5)
    (= (capacity a4) 2500)
    (= (refuel-rate a4) 1)

    (= (fuel a5) 1000)
    (= (slow-speed a5) 20)
    (= (fast-speed a5) 30)
    (= (slow-burn a5) 2)
    (= (fast-burn a5) 3)
    (= (capacity a5) 1500)
    (= (refuel-rate a5) 1)

    (= (fuel a6) 2000)
    (= (slow-speed a6) 5)
    (= (fast-speed a6) 60)
    (= (slow-burn a6) 2)
    (= (fast-burn a6) 6)
    (= (capacity a6) 4000)
    (= (refuel-rate a6) 1)

    (= (fuel a7) 4000)
    (= (slow-speed a7) 20)
    (= (fast-speed a7) 70)
    (= (slow-burn a7) 2)
    (= (fast-burn a7) 7)
    (= (capacity a7) 4500)
    (= (refuel-rate a7) 1)

    (= (total-fuel-used a1) 0)
    (= (total-fuel-used a2) 0)
    (= (total-fuel-used a3) 0)
    (= (total-fuel-used a4) 0)
    (= (total-fuel-used a5) 0)
    (= (total-fuel-used a6) 0)
    (= (total-fuel-used a7) 0)

    (= (boarding-time) 1)
    (= (debarking-time) 1)
 )


(:tasks-goal
   :tasks(
       (transport-person p1 cadiz)
       (transport-person p2 cadiz)
       (transport-person p3 cadiz)
       (transport-person p4 cadiz)
       (transport-person p5 cadiz)
       (transport-person p6 granada)
       (transport-person p7 granada)
       (transport-person p8 granada)
       (transport-person p9 granada)
       (transport-person p10 granada)
       (transport-person p11 jaen)
       (transport-person p12 jaen)
       (transport-person p13 jaen)
       (transport-person p14 jaen)
       (transport-person p15 jaen)
       (transport-person p16 bilbao)
       (transport-person p17 bilbao)
       (transport-person p18 bilbao)
       (transport-person p19 bilbao)
       (transport-person p20 bilbao)
       (transport-person p21 cordoba)
       (transport-person p22 cordoba)
       (transport-person p23 huelva)
       (transport-person p24 huelva)
       (transport-person p25 huelva)
   )
  )
)
